### ISSUE TITLE
Your request to provision  "Microsoft 365 learning pathways"  template failed!  Please report the issue here providing the following provisioning action correlation ID: 91379670-0627-4dd7-8518-84fe0b160c79 !

### ISSUE THREAD

**Issue by vandewoe** [SharePoint/sp-provisioning-service#224]

**Comment by ArmaanDhingra** [comment]
action correlation ID: 214523e2-d498-40b0-8728-f54000348c19
Facing the problem that upon trying to provision a new site, it failed to complete.
Note: I previously had a site with the same name: https://dvi.sharepoint.com/teams/Innovation_CoE
I deleted this site because I wanted to apply a different template from Microsoft Lookbook designs. To do this and maintain the same URL, I had to delete the old site and then I immediately requested to provision the new one using the desired template ("Global Marketing Hub").

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.
