### ISSUE TITLE
Your request to provision "Staff home page" template failed!

### ISSUE THREAD

**Issue by jjosepagan** [SharePoint/sp-provisioning-service#254]
Please report the issue providing the following provisioning action correlation ID: 3155d9b9-9310-4d35-a21d-bf92fb22205d !

I tried to include the "Staff Home page" using this URL : https://fundacioneducacioncatolica.sharepoint.com/sites/DepartamentoXtrafec2

**Comment by rkandasamy1** [comment]
I have a similar issue, but mine is with the class home page. Funny thing is, I was able to add the staff and school template with the same priveleges. I don't know how.
Here's the contents of the email I received:
Your request to provision "Class home page" template failed!
Please report the issue here providing the following provisioning action correlation ID: 6f25e8cc-22d3-4fd1-b975-0966ca221a40 !

**Comment by PaoloPia** [comment]
Hi @jjosepagan,
Thanks for your feedback. It looks like you tried to apply the template onto a site which has not been created with English (1033) as the primary language. In fact, the provisioning failed while applying the Regional settings. Please, try again providing the URL of site created with English as the main language. Thanks.

**Comment by PaoloPia** [comment]
In case of any further exception, please open another issue providing the new PnP Correlation ID.
