### ISSUE TITLE
Installazione template "Staff home page" non riuscita 

### ISSUE THREAD

**Issue by gherardo76** [SharePoint/sp-provisioning-service#263]
**Describe the issue**
Non sono riuscito ad installare il template sul Tenant

**Details (please complete the following information):**
ID: 89e797bf-a81f-41c3-ba5f-ce11b314ac77

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Based on the event log, we see that the provisioning failed due to an "Access Denied" exception. Please, verify that you are the Owner of the site where you are provisioning the template, and avoid using the content of the site while provisioning is running (because you could accidentally lock some of the files). Please try again, and let us know in case of any issue (creating a new issue and providing another PnP Correlation ID). In the meantime, I will close this issue. Thanks.
