### ISSUE TITLE
Request to provision New Employee Onboarding Hub template failed

### ISSUE THREAD

**Issue by rjgeeky** [SharePoint/sp-provisioning-service#264]
I was logged in with tenant global admin ID and chose to provision the NEO SharePoint template. However, this ended with an error after several minutes.

**Exception ID:** The remote server returned an error: (401) Unauthorized.
**Provisioning action correlation ID:** 63b463ed-7220-4255-bf4f-ad94db7142ec

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Based on the log, the exception was "(401) Unauthorized.". Please, verify that you are the Owner of the site where you are provisioning the template, and avoid using the content of the site while provisioning is running (because you could accidentally lock some of the files). Please try again, and let us know in case of any issue (creating a new issue and providing another PnP Correlation ID). In the meantime, I will close this issue. Thanks.

**Comment by rjgeeky** [comment]
Thanks for the response. As I mentioned, I'm a tenant global admin and hence have access to provision the four sites that the NEO template creates. Based on your response I was about to attempt provisioning again but on a hunch, I checked for the sites first. To my surprise, the sites have been created and seem to be working without issues. You may want to look at why an error was thrown even though the job completed successfully.
