### ISSUE TITLE
Your request to provision "Leadership Connection"  template failed!

### ISSUE THREAD

**Issue by Gweeeep** [SharePoint/sp-provisioning-service#280]
Your request to provision
"Leadership Connection" 
template failed!
Please report the issue here providing the following provisioning action correlation ID: 3f9048e0-5655-4db6-bfce-16adf9364d4a !

**Comment by VesaJuvonen** [comment]
This was caused by permission issue after applying the template on top of existing site. Typical issues causing this would be for example pages which are on edit mode etc. This is why we highly recommend to not apply the templates on top of existing sites since there can be complications like this one. Would suggest either to use new empty URL or ensure that the pages in the used site are not in edit mode.
