### ISSUE TITLE
Provision "Leadership Connection"  template failed!

### ISSUE THREAD

**Issue by fauzanh** [SharePoint/sp-provisioning-service#282]
Site creation failed when I try to provision "Leadership Connection" template.

- PnP Correlation ID: 2af4e6d5-bdcb-408c-9294-26250927302f 
- Reference Template: https://lookbook.microsoft.com/details/c19f437b-35ca-42f2-b27a-1caa49ad8bde
- Primary language of the target tenant: en-us
- Are you using a Tenant Global Admin account to provision the template: Yes

**Comment by VesaJuvonen** [comment]
hi @fauzanh,
this was caused by runtime exception in SharePoint Online as there was already an URL in the tenant recycle bin with the same URL you requested this site to be created. This is a situation which we can only detect during provisioning time and only way to avoid this is by deleting the old site collection from the recycle bin or by using alternative URL.
