### ISSUE TITLE
Your request to provision "New Employee Onboarding Hub"  template failed!

### ISSUE THREAD

**Issue by LukeOHardman** [SharePoint/sp-provisioning-service#283]
**Describe the issue**
Look Book on Boarding Template failed

**Details (please complete the following information):**
correlation ID: 2cb86a7d-97c1-4841-b02d-4206e1a0c42a 
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/75e60a32-9849-4ed4-b83e-b2b08983ad19
- Primary language of the target tenant: [provide the LCID of the primary language of the target tenant] English
Am Global Admin
**Additional context**

**Comment by VesaJuvonen** [comment]
This particular failure was caused by the /sites/NewEmployeeOnboarding site collection being in the tenant recycle bin, which means that we cannot re-create the site collection with the same suggested URLs. We suggest deleting the site collections from tenant recycle bin or using alternative URLs when provisioning in provisioning form.

If issue remains, please submit a new issue with updated correlation ID.
