### ISSUE TITLE
Microsoft Permissions requested following on from Issue #55

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/sp-provisioning-service#284]
Describe the issue

There are alot of permissions here. given extreme permissions sought, has PnP been security tested?
![PnPPermissionsIssue](https://user-images.githubusercontent.com/8484048/91187661-5325aa80-e6e8-11ea-9b3c-d89327ea8389.png)

What is best practise here to use the App or the PnP-PowerShell

**Add any other context about the problem here.**

Alot of companies I work with get nervous when they see alot of permission requests.
So I am getting asked this question alot now.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately, in order to being able to provision sites and settings at tenant level, we need all the above permissions. If you don't want to grant those permissions, you can download the template from here (https://github.com/SharePoint/sp-dev-provisioning-templates) and apply it manually in PowerShell. Thanks.
