### ISSUE TITLE
Unable to apply Staff home page template

### ISSUE THREAD

**Issue by ekrizon** [SharePoint/sp-provisioning-service#316]
Unable to apply staff home page template. Error email received, your request to provision "Staff home page" template failed!

![image](https://user-images.githubusercontent.com/20015781/94837279-4bd17b00-03d1-11eb-9ea2-9fb6bb453eff.png)

- PnP Correlation ID: c46c1f62-daac-42d6-96ea-36405814fba8
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/eb5d4741-e2f4-44f1-954b-e7d598585c63
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: Yes

I am site owner and accepted the PnP permission request when it prompted after clicking "Add to your tenant"
![image](https://user-images.githubusercontent.com/20015781/94837428-78859280-03d1-11eb-9eda-7a5811f3a7ec.png)

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that you created a Communication Site, instead of a Team Site. As such, the provisioning failed. Could you please try again, targeting a fresh new Team site? For further details, you can follow the instructions provided here: https://go.microsoft.com/fwlink/?linkid=2135144. In case of any issue, please create another item here and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
