### ISSUE TITLE
Once again template partially failed 

### ISSUE THREAD

**Issue by emmagodo** [SharePoint/sp-provisioning-service#345]
**Describe the issue**
Partially failing in provisioning of template. I have tried it several times now. once again it failed: ID: 2f2ed0ea-7102-4c10-80b8-33c1a205d094

second time I'm creating a report - by request from last issue report.

**Comment by balle3201** [comment]
Same issue here unfortunately. I have tried to provision the Microsoft 365 Learning Pathways several times, and it always fails with the following correlation IDs:

- de5badf2-2b50-4d2e-aa7e-16dd9c6bc4f7
- 9606de0a-009c-4983-984b-9d965331987d
- 446e1f45-7577-4571-a0da-7f084029f874

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see - based on the provided Correlation ID - that the exception was (all the times) due to a socket connection issue while trying to connect with the sites.asmx web service. As such, it seems to be a random hiccup on the SharePoint side. Hence, the only thing that I can say is to try again. Thanks for your cooperation.
