### ISSUE TITLE
Partially Failed Provision

### ISSUE THREAD

**Issue by kameshm05** [SharePoint/sp-provisioning-service#376]
It is my second attempt. I am trying to load School home page to communication site . But i got the following error and correlatio ID.
Please report the issue here providing the following provisioning action correlation ID: 76b7a1dd-2e95-4a74-a0e0-143a9a974b78 !

**Comment by PaoloPia** [comment]
Hi @kameshm05,
Thanks for using the Look Book site. Based on the log I can see that the issue was an "Access Denied" while trying to upload an image on the target site. In the last few weeks, we've been experiencing some issues related to files upload and we're working on making the provisioning engine stronger. In the meantime, you can only try again or wait. I'm sorry. Thanks for your cooperation.

**Comment by HiltonGiesenow** [comment]
I don't know if this is relevant to you, but I was having trouble and it finally worked when I tried in another tenant - I was using one of the "demo" tenants Microsoft offers, and when I switched to another type of tenant (an Office/Microsoft 365 "developer" tenant) then it worked fine - see here for how to get one - https://developer.microsoft.com/en-us/microsoft-365/dev-program

**Comment by VioletteBowhay** [comment]
We have encountered the same issue occurring on the Sales Hub and Retail Operations looks.
The Human Resources Hub provisions without issue in the same tenant. We do have a second tenant and the Sales Hub does delpoy there.

Correlation on the last error was: 969b4fcf-a351-491b-82a6-21326695c2fe
