### ISSUE TITLE
Microsoft 365 learning pathways tempate failed

### ISSUE THREAD

**Issue by JChristopherNZ** [SharePoint/sp-provisioning-service#382]
Provisioning action correlation ID: 8e63ad32-4cfe-479a-b5b0-3bd81446ade5

**Comment by JChristopherNZ** [comment]
Failed a second time too - Deployment failed.  Correlation ID: f6a3a39f-5090-b000-3449-2427f767f787

**Comment by PaoloPia** [comment]
Hi @JChristopherNZ,
Thanks for using the Look Book site. Based on the log I can see that the issue was an "Access Denied" while trying to upload an image on the target site. In the last few weeks, we've been experiencing some issues related to files upload and we're working on making the provisioning engine stronger. In the meantime, you can only try again or wait. I'm sorry. Thanks for your cooperation.
