### ISSUE TITLE
Non Admins are able to provision sites using Microsoft Lookbooks

### ISSUE THREAD

**Issue by cchandler09** [SharePoint/sp-provisioning-service#383]
**Describe the issue**
Tested this in two separate tenants and got the same behavior each time. End users that have no admin access are able to provision sites using Microsoft Lookbooks. The Tenants have O365 Group Creation and Site Creation locked down and there is no other method users can use to provision the sites. 

**Expected behavior**
The templates mention that the users need to be a Tenant Administrator to deploy the template but end users that are not administrators (tested in two tenants with multiple end user accounts) are able to provision this. There is a pre-requisite check that is done when you go to deploy the templates that I would expect to verify if this is possible. 

https://lookbook.microsoft.com/details/34756b7e-e6f6-4327-ba4a-96494a50dca3

**Details (please complete the following information):**
- PnP Correlation ID: n/a
- Reference Template: https://lookbook.microsoft.com/details/34756b7e-e6f6-4327-ba4a-96494a50dca3
- Primary language of the target tenant: 
- Are you using a Tenant Global Admin account to provision the template: No

**Additional context**
We reached out to Microsoft Support and they referred us here. We need clarification on how to lock this down as end users shouldn't be able to provision these.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Unfortunately, what you experience (non-admin users can provision some of the templates) is by design. If you don't want to allow that, you could for example block access to the Look Book site via your own network rules. Another option is to restrict the app in Azure Active Directory (https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-restrict-your-app-to-a-set-of-users). Thanks.
