### ISSUE TITLE
Unable to provision template, fail at start

### ISSUE THREAD

**Issue by svoky7334** [SharePoint/sp-provisioning-service#421]
**Describe the issue**
We are trying to provision below templates to the production but we receive an error at the beginning.
https://lookbook.microsoft.com/details/388a159f-475b-4557-9088-c9073a26c576
https://lookbook.microsoft.com/details/99d3b7ea-6ca0-430e-96bc-922d4d2de2ab

They both fail, also we have tried another preonbording site and the result is the same.
The templates are successfully provisioned on the test tenant and we have the account with Global Administrator rights.

**Expected behavior**
Successfully provisioned sites like on the test tenant.

**Details (please complete the following information):**
- PnP Correlation ID: 
- 168e62b3-161f-42be-9783-23a058228a9f !
-  baba57a0-6d98-44ef-92b8-0f1999189bfe !
- a56ac518-5259-4c0d-b34a-96455bf0b340 !
- 7d48f886-d928-4f55-bae6-fc125ef7873a !
- 3454a3c1-30fe-4df8-8069-abeb495c7648 !
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/388a159f-475b-4557-9088-c9073a26c576
https://lookbook.microsoft.com/details/99d3b7ea-6ca0-430e-96bc-922d4d2de2ab
- Primary language of the target tenant: English
- Are you using a Tenant Global Admin account to provision the template: YES
![provisioningmail](https://user-images.githubusercontent.com/80774153/111355078-4d44e600-8687-11eb-98f8-b340973f7c69.png)

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that your company has a vanity domain, which is not supported by the Provisioning Service. In order to provision the templates on your tenant, you should download the packages from the source GitHub repository (for NEO: https://github.com/SharePoint/sp-dev-provisioning-templates/tree/master/tenant/NEO-main, https://github.com/SharePoint/sp-dev-provisioning-templates/tree/master/tenant/NEO-departmental, and https://github.com/SharePoint/sp-dev-provisioning-templates/tree/master/tenant/NEO-preonboarding) and apply them using PnP PowerShell (https://pnp.github.io/powershell/). Thanks for your cooperation.
