### ISSUE TITLE
Microsoft LookBook Sharepoint provisioning Failure #2

### ISSUE THREAD

**Issue by scolenbrander** [SharePoint/sp-provisioning-service#422]
**Describe the issue**
Your request to provision "Staff home page" template failed!

**Expected behavior** 
Provisioning Completed

**Screenshots**
See attachment

**Details (please complete the following information):**
- PnP Correlation ID: [ID: d540be55-52b1-4e6a-92b5-d02e6674a512 !]
- Reference Template: [https://lookbook.microsoft.com/site/home/provision?packageId=eb5d4741-e2f4-44f1-954b-e7d598585c63&returnUrl=https%3A%2F%2Flookbook.microsoft.com%2Fdetails%2Feb5d4741-e2f4-44f1-954b-e7d598585c63}]
- Primary language of the target tenant: [Dutch]
- Are you using a Tenant Global Admin account to provision the template: [Yes]

**Additional context**
![Schermafbeelding 2021-03-17 170111](https://user-images.githubusercontent.com/80757214/111498885-ac1b6580-8742-11eb-9e1f-675a5b58107f.jpg)

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the log I can see that the issue was an "Access Denied" while trying to upload an image on the target site. In the last few weeks, we've been experiencing some issues related to files upload and we're working on making the provisioning engine stronger. In the meantime, you can only try again or wait. I'm sorry. Thanks for your cooperation.
