### ISSUE TITLE
Microsoft 365 learning pathways  template failed

### ISSUE THREAD

**Issue by jescc** [SharePoint/sp-provisioning-service#513]
**Describe the issue**
Microsoft 365 learning pathways  template failed

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
- PnP Correlation ID: eda882f2-2927-495e-bb74-e223a6c9610d 
- Reference Template: [please provide the URL of the template in the Look book site. It should be something like: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: spanish es
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. We've just updated the provisioning service with several fixes. Hopefully, this one is now solved or at least mitigated. Please try again and let us know in case of any further issues. Thanks for your cooperation.

**Comment by sscarcella** [comment]
It is the same result, this time said that it finished successfully instead of partially, but it is still different than the site in the example and is not in English and missing dropdown on the second menu item...

see screenshot



________________________________

**Comment by sscarcella** [comment]
Your request to provision

"Microsoft 365 learning pathways"

template failed!

Please report the issue here<https://link.edgepilot.com/s/f85fe493/lD0Yw5UH9E2IX9_V4EviBQ?u=http://aka.ms/provisioning-issue> providing the following provisioning action correlation ID: e28da659-ea78-4173-a869-40962bbe3b8b !


________________________________
