### ISSUE TITLE
Learning Pathways installation fails

### ISSUE THREAD

**Issue by Ron-Rohlfs** [SharePoint/sp-provisioning-service#540]
**Describe the issue**
Learning Pathway installation gives an error and is incomplete. The resulting site looks a generic Communication site.

The provisioning service shows errors, and M365lpConfiguration.ps1 completes without error. However, installation looks incomplete in both cases.

**Expected behavior**
Expect to see the home page configured for learning pathway with top navigation and web parts.

**Screenshots**
Expected learning pathways Site home page:
![Expected Home page](https://user-images.githubusercontent.com/83991071/121813194-cec4f980-cc1f-11eb-96e1-0c83ce681f68.PNG)

Expected learning pathways Site contents:
![Expected Site contents](https://user-images.githubusercontent.com/83991071/121813203-da182500-cc1f-11eb-9511-beb4f8d3340b.PNG)

Incorrect site home page:
![Incorrect Home page](https://user-images.githubusercontent.com/83991071/121813241-151a5880-cc20-11eb-8a6c-8eb8bd090363.PNG)

Incorrect Site contents:
![Incorrect Site contents](https://user-images.githubusercontent.com/83991071/121813248-25cace80-cc20-11eb-8018-e47478e2eed5.PNG)

**Details (please complete the following information):**
- PnP Correlation ID: [Provide a correlation ID for the provisioning action]
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: 1033
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**
It appears the installation is incomplete. Content is not added, and the home page is not configured.

**Comment by Ron-Rohlfs** [comment]
More failed attempts
06142020 [7:59 AM] Goodwin, Mark (Extranet) correlation ID: 7f3697a5-6ed7-470e-aef4-4efe0a9fd4be !
[8:35 AM] Goodwin, Mark (Extranet) correlation ID: b2cd8c1a-8d9a-42d7-a72c-024bbfa92101

**Comment by Ron-Rohlfs** [comment]
Console errors:
![Console errors](https://user-images.githubusercontent.com/83991071/121925268-98f04580-ccf1-11eb-976b-30f786047cee.PNG)

network metadata
![network metadata](https://user-images.githubusercontent.com/83991071/121925317-a6a5cb00-ccf1-11eb-83ee-bcb22b04375e.PNG)

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. In the event log, we can see - based on the provided Correlation IDs - that the first try failed with an exception while trying to upload the solution package in the App Catalog, while the second try failed because you targeted an already existing site (most likely the one you used in the first attempt) because the site was not accessible. Could you please try provisioning the solution again to a different site URL and eventually clean up the App Catalog, just in case the solution package is already there? In case of any other issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
