### ISSUE TITLE
Request to provision"Global marketing hub" template failed!

### ISSUE THREAD

**Issue by holyman1010** [SharePoint/sp-provisioning-service#558]
I had tried several times to install this template, but it keeps failing, I also search the other similar issues, but I can't find the recycle bins and change no matter what URL still fails.

@PaoloPia, Can you help me to find a way to install this template? Thank you.

provisioning action correlation ID: d98a690b-5363-4c5c-83a6-0980bbc6529e

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Inpsecting the event log, we can see - based on the provided Correlation ID - that the provisioning failed while creating the target Communication Site (the exception was 403 - "Forbidden"). Could you please try to provision the solution to a different site URL or with a different user account? In case of any issue, please create another item and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.

**Comment by holyman1010** [comment]
Hi PaoloPia, Thanks for your reply,

Our admin also doesn't know how to help me to use another different tenant,

Can I create a Global marketing hub without creating a Communication Site at the same time?

Because other theme doesn't require creating a Communication Site and still can build a theme sample page.

Can you help just cancel the Communication Site condition when creating a Global marketing hub site? 

Thank you,

**Comment by PaoloPia** [comment]
Hi,
Unfortunately, I cannot change a global template in order to accomplish your requirements. However, if you join the Office Developer Program (https://developer.microsoft.com/en-us/microsoft-365/dev-program) you can create a new developer tenant and use it for testing purposes. Please, try to do so and to provision the site there. In case of any further issue with the new tenant, please open a new ticket. Thanks.
