### ISSUE TITLE
Microsoft 365 learning pathways

### ISSUE THREAD

**Issue by admemh** [SharePoint/sp-provisioning-service#574]
Hello,
When i try to add the learning Pathways to my tenant, i have an error message who sait that : 
**Unfortunately your site provisioning at least partially failed!** 

The correlation ID: 2c8150a6-d842-4d5f-bd81-0ac1f3943b45 !
<img width="744" alt="erreur LP" src="https://user-images.githubusercontent.com/89460615/130615510-67db1cd3-3808-407b-8553-d8aca4391468.PNG">

**Comment by Breakthrough-it-subscriptions** [comment]
Same here. Trying to add Learning Pathways. Just providsioned app catalog, which completed successfully. Kicked off provision of Learning Pathways and got:
Your request to provision"Microsoft 365 learning pathways" template failed!
Please report the issue here providing the following provisioning action correlation ID: dcf6428d-ea6d-43c3-9d80-4de0bdee9122 !

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Based on the event log, we can see that both the failures are related to the deployment of the SPPKG package of Learning Pathways. For @admemh the problem is about permissions. In fact, the error message states "Seuls les utilisateurs pouvant consulter des pages peuvent afficher la liste des applications". For @Breakthrough-it-subscriptions  the error happens while trying to upload the file in the App Catalog. Could you both please double check your permissions in the App Catalog, remove any already existing customlearning.sppkg file from the App Catalog, and try to provision the solution again, eventually using a different site URL? In case of any issue, please create another item in this issues list and provide the corresponding Correlation ID for further investigation. Thanks for your cooperation.
