### ISSUE TITLE
Failed to create a MLP Site

### ISSUE THREAD

**Issue by vinayshekhar-github** [SharePoint/sp-provisioning-service#605]
Hi Team
Getting an error while provisioning MLP. Please check if there is a bug and resolve asap as customers are also reporting the same. 
"Unfortunately your site provisioning at least partially failed!" Screenshot attached[](url
![MLP Failed](https://user-images.githubusercontent.com/50832449/143534923-d093f912-560a-4062-9e0b-fdfb39ef2409.jpg)
)
![MLP Failed](https://user-images.githubusercontent.com/50832449/143534951-71bcd100-b5a3-4b39-89ab-f043885e7bfb.jpg)

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. We've just refreshed the solution and I invite you to test it now. In case of any problem, please create a new issue and provide the PnP Correlation ID (that you get by email together with the provisioning outcome), so that we can investigate it further. Thanks.
