### ISSUE TITLE
LP wont provision over STS#0 template

### ISSUE THREAD

**Issue by ferocity99** [SharePoint/sp-provisioning-service#702]
**Describe the issue**
As the process for lookbooks has changed we moved to deploying via pnp.  The creation of a communication site is now apparently based on the STS#0 template not the SITEPAGEPUBLISHING#0.  This means the Learning pathways site will NOT deploy.  Can the initial template be changed to reflect the new base templates?

**Comment by ferocity99** [comment]
![image](https://github.com/SharePoint/sp-provisioning-service/assets/6934193/9d3fa746-ba9a-40b1-abd9-438f71571d98)

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the Look Book site. Please, simply follow instructions provided in the article (https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/applying-pnp-templates) referenced by the site to provision the Learning Pathways site. You can also watch the video provided in the above document to see the step by step guidance for provisioning the LP site. Thanks.

**Comment by ferocity99** [comment]
@PaoloPia  the answer hasn’t been posted.  The process has changed yes but the new process is broken.  When creating a new communication site it creates on a different base template STS#0 not the original one SITEPAGEPUBLISHING#0.  
we cannot use this process to overlay the learning profiles template.  It doesn’t work, please provide a solution not just point me at a page that doesn’t have one.

**Comment by PaoloPia** [comment]
@ferocity99 I'm sorry but I'm not sure that I'm understanding what the problem is. The LP site is based on a Communication Site template, if you follow the instructions provided in the document or even better you watch the video provided with the document, you will see a step by step guidance about how to provision the LP site (the demo in the video is precisely about provisioning LP). The guidance works as you can see watching the video, and I just tried it one more time now, and it works. Please, let me know if there is anything else that I can do to help you.

**Comment by ferocity99** [comment]
When i provision a communications site it works fine.  When i go through the pnp provisioning details it errors saying the communication site has been provisioned with an STS#0 base template not a SITEPAGEPUBLISHING#0.  Following the instructions is not helping as there is a problem with them.  The video is not helpful as it points to the same process i've tried multiple times.  
The issue is with the base template.  It won't load the site over a different base template.  I posted the snip of the comment above.
